[project]
name = "cvbox"
authors = [
  { name="Kelvin Kong", email="kelvin86@gmail.com" }
]
license = {text="Apache-2.0"}


[project.urls]
"Homepage" = "https://github.com/kelvinAI/cvbox"
"Bug Tracker" = "https://github.com/kelvinAI/cvbox"